<?php


namespace Hillel\Model;


use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{   use SoftDeletes;

    public function posts()
    {
        return $this->hasMany(post::class);
    }


    public function delete()
    {

        if ($this->id == 0) {
            echo "You can't delete this speshial category";
            return false;
        }
        \Hillel\Model\Post::where('category_id',$this->id)->update(['category_id' => 0]);


        return parent::delete(); // TODO: Change the autogenerated stub
    }
}