<?php


namespace Hillel\Model;


use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{  use SoftDeletes;

    public function category()
    {
        return $this->belongsTo(category::class);
    }

    public function tags()
    {
        return $this->belongsToMany(tag::class)->withTimestamps();
    }

    public function delete()
    {
        $this->tags()->detach();

        return parent::delete(); // TODO: Change the autogenerated stub
    }
}