<?php


namespace Hillel\Model;


use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Tag extends Model
{   use SoftDeletes;

    public function posts()
    {
        return $this->belongsToMany(post::class)->withTimestamps();
    }

    public function delete()
    {
        $this->posts()->detach();

        return parent::delete(); // TODO: Change the autogenerated stub
    }

}